# Generated by Django 4.2.6 on 2024-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_rutaaprendizaje_curso_ruta_aprendizaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaaprendizaje',
            name='descripcion',
            field=models.TextField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
