# Generated by Django 4.2.6 on 2024-01-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_rutaaprendizaje_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='identificacion',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
