# Generated by Django 4.2.6 on 2024-01-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0009_alter_estudiante_did_alter_instructor_did_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microcredencial',
            name='oferta_academica',
        ),
        migrations.CreateModel(
            name='ParticipacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.estudiante')),
                ('oferta_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.ofertaacademica')),
            ],
        ),
        migrations.AddField(
            model_name='microcredencial',
            name='inscripcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certificados.participacioncurso'),
            preserve_default=False,
        ),
    ]
