# Generated by Django 4.2.6 on 2024-01-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0010_remove_microcredencial_oferta_academica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacioncurso',
            name='estado',
            field=models.CharField(blank=True, choices=[('aprobado', 'APROBADO'), ('reprobado', 'REPROBADO'), ('validado', 'VALIDADO')], max_length=255, null=True),
        ),
    ]
