# Generated by Django 4.2.6 on 2024-01-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhaincertapp', '0002_estudiante_identificacion_alter_estudiante_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='resultado_aprendizaje',
            field=models.TextField(max_length=1024),
        ),
        migrations.DeleteModel(
            name='ResultadoDeAprendizaje',
        ),
    ]
