# Generated by Django 4.2.6 on 2024-01-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educhaincertapp', '0003_alter_curso_resultado_aprendizaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educhaincertapp.universidad')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='ruta_aprendizaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educhaincertapp.rutaaprendizaje'),
            preserve_default=False,
        ),
    ]
