# Generated by Django 4.2.6 on 2024-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhaincertapp', '0008_estudiante_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='did',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='did',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='microcredencial',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadorganizativa',
            name='did',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='did',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
