# Generated by Django 4.2.6 on 2024-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhaincertapp', '0011_alter_participacioncurso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcredencial',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='microcredencial',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='microcredencial',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
