# Generated by Django 4.2.6 on 2024-01-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educhaincertapp', '0012_microcredencial_estado_microcredencial_ipfs_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microcredencial',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='microcredencial',
            name='universidad',
        ),
    ]
