# Generated by Django 4.2.6 on 2024-01-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhaincertapp', '0016_rename_participacion_microcredencial_participacion_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcredencial',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microcredencial',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
